#!/usr/bin/env zsh
# 測定回数
run_count=5

# 指定した回数の測定を行い、結果を出力する
run_measurement() {
  for i in {1..$1}; do
    /usr/bin/time -p zsh -i -c exit 2>&1 >/dev/null \
      | awk '/^real/{print $2}'
  done
}

# 起動速度を測定して集計
run_measurement ${run_count} \
  | awk '
    BEGIN {
      sum=0;
      min=999;
      max=0;
      n=0;
    }
    {
      printf "%2d: %6.3f s\n", NR, $1;
      v=$1;
      sum+=v;
      if(v<min) min=v;
      if(v>max) max=v;
      n++;
    }
    END {
      print "----"
      printf "avg: %6.3f s\nmin: %6.3f s\nmax: %6.3f s\n", sum/n, min, max
    }
  '
